###########################
#        Templates        #
###########################
templates:
    Movie:
        tmdb_collection: <<collection>>
        tmdb_summary: <<summary>>
        url_poster: <<poster>>
        sort_title: ++++_<<collection_name>>
        collection_order: release
    people:
        actor: tmdb
        tmdb_person: <<person>>
        sort_title: ++_<<collection_name>>
        collection_order: release
    director:
        director: tmdb
        tmdb_person: <<person>>
        sort_title: ++_<<collection_name>>
        collection_order: release
    Collection:
        optional:
          - collection
          - movie
        tmdb_collection_details: <<collection>>
        tmdb_movie: <<movie>>
        sort_title: ++++_<<collection_name>>
        sync_mode: sync
        collection_order: release
collections:
###########################
#    Movie Collections    #
###########################
  James Bond:
    template: {name: Movie, collection: 645, summary: 645, poster: https://theposterdb.com/api/assets/115662}
  X-Men:
    template: {name: Movie, collection: 748, summary: 748, poster: https://theposterdb.com/api/assets/20 }
  Mission Impossible:
    template: {name: Movie, collection: 87359, summary: 87359, poster: https://theposterdb.com/api/assets/65202}
  Pirates of the Caribbean:
    template: {name: Movie, collection: 295, summary: 295, poster: https://theposterdb.com/api/assets/71934}
  Jurassic Park:
    template: {name: Movie, collection: 328, summary: 328, poster: https://theposterdb.com/api/assets/45080}
  Harry Potter:
    template: {name: Movie, collection: 1241, summary: 1241, poster: https://theposterdb.com/api/assets/737}
  Star Wars:
    template: {name: Movie, collection: 10, summary: 10, poster: https://theposterdb.com/api/assets/1409}
  Star Trek:
    #template: {name: Movie, collection: "151, 115575, 115570", poster: https://theposterdb.com/api/assets/23563}
    url_poster: https://theposterdb.com/api/assets/23563
    sort_title: ++++_Star Trek
    collection_order: release
    sync_mode: sync
    imdb_list: https://www.imdb.com/list/ls506310059/?ref_=tt_rls_4
    summary: "A collection of all Star Trek movies"
###########################
#    People Collections   #
###########################
  Alfred Hitchcock:
    template: {name: director, person: 2636}
    #trakt_list: https://trakt.tv/users/movistapp/lists/hitchcock
  Christopher Nolan:
    template: {name: director, person: 525}
  Christopher Guest:
    actor: tmdb
    template: {name: director, person: 13524}
  Coen Brothers:
    writer: tmdb
    template: {name: director, person: "1223, 1224"}
    summary: "Joel Coen and Ethan Coen, collectively referred to as the Coen Brothers, are American film directors, producers, screenwriters, and editors. Their films span many genres and styles, which they frequently subvert or parody. Their most acclaimed works include: Raising Arizona (1987), Miller's Crossing (1990), Fargo (1996), The Big Lebowski (1998), O Brother, Where Art Thou? (2000), No Country for Old Men (2007), Burn After Reading (2008), A Serious Man (2009), True Grit (2010), Inside Llewyn Davis (2013), and The Ballad of Buster Scruggs (2018)."
  David Fincher:
    template: {name: director, person: 7467}
  J.J. Abrams:
    template: {name: director, person: 15344}
  James Cameron:
    template: {name: director, person: 2710}
  Martin Scorsese:
    template: {name: director, person: 1032}
  M. Night Shyamalan:
    template: {name: director, person: 11614}
  Mel Brooks:
    writer: tmdb
    template: {name: director, person: 14639}
  Paul Thomas Anderson:
    writer: tmdb
    template: {name: director, person: 4762}
  Nicolas Cage:
    template: {name: people, person: 2963}
  Quentin Tarantino:
    template: {name: director, person: 138}
  Ridley Scott:
    template: {name: director, person: 578}
  Steven Spielberg:
    template: {name: director, person: 488}
  Tim Burton:
    writer: tmdb
    template: {name: director, person: 510}
  Wes Anderson:
    writer: tmdb
    template: {name: director, person: 5655}
###########################
#    Movie Collections   #
###########################
  Alien:
    template: {name: Collection, collection: "8091, 135416"}
  Austin Powers:
    template: {name: Collection, collection: 1006}
  Back to the Future:
    template: {name: Collection, collection: 264}
  The Fast and the Furious:
    template: {name: Collection, collection: "9485, 688042"}
  The Godfather:
    template: {name: Collection, collection: 230}
  The Hunger Games:
    template: {name: Collection, collection: 131635}
  Indiana Jones:
    template: {name: Collection, collection: 84}
  Jason Bourne:
    template: {name: Collection, collection: 31562}
  John Wick:
    template: {name: Collection, collection: 404609}
  The Lord of the Rings:
    template: {name: Collection, collection: 119}
  Ocean's 11:
    template: {name: Collection, collection: 304}
  Rambo:
    template: {name: Collection, collection: 5039}
  Saw:
    template: {name: Collection, collection: 656}
  Mad Max:
    template: {name: Collection, collection: 8945}
  Bad Boys:
    template: {name: Collection, collection: 14890}
  Bad Moms:
    template: {name: Collection, collection: 487376}
  Batman:
    template: {name: Collection, collection: 120794}
  Bill & Ted:
    template: {name: Collection, collection: 91746}
  The Dark Knight:
    template: {name: Collection, collection: 263}
  Deadpool:
    template: {name: Collection, collection: 448150, movie: 567604}
  Die Hard:
    template: {name: Collection, collection: 1570}
  Has Fallen:
    template: {name: Collection, collection: 386534}
  The Hobbit:
    template: {name: Collection, collection: 121938}
  Jumanji:
    template: {name: Collection, collection: 495527}
  Jump Street:
    template: {name: Collection, collection: 212562}
  The Matrix:
    template: {name: Collection, collection: 2344}
  Monty Python:
    template: {name: Collection}
    imdb_list: https://www.imdb.com/list/ls072012494/
    summary: Monty Python is a British surreal comedy troupe who created sketch comedy television shows and movies
  The Mummy:
    template: {name: Collection, collection: 1733}
  National Treasure:
    template: {name: Collection, collection: 52984}
  Neighbors:
    template: {name: Collection, collection: 400700}
  Now You See Me:
    template: {name: Collection, collection: 382685}
  Planet of the Apes:
    template: {name: Collection, collection: 173710}
  Sherlock Holmes:
    template: {name: Collection, collection: 102322}
  Taken:
    template: {name: Collection, collection: 135483}
# Bruce Lee
# Criterion
# DC
# Godzilla
# Ken Burns
# Police Academy
# The Ring
# Three Colors
# Tremors
# Zataoichi
# Marvel